### ISSUE TITLE
Getting 500 

### ISSUE THREAD

**Issue by krstivoja** [WPManageNinja/fluent-smtp#129]
If the DPlugins Collaboration plugin is turned on I am getting 500 error if I want to send email. 

It is strange since Collaboration because already prefix vendors

![rn_image_picker_lib_temp_1c04846f-1d1b-41a9-b760-1c639d546c40](https://user-images.githubusercontent.com/1234350/191941562-b7575609-177b-4499-9f8e-3a9c37ab4a19.png)

This is the error we are getting
<img width="2096" alt="Screenshot 2022-09-23 at 11 14 45" src="https://user-images.githubusercontent.com/1234350/191941663-8360e9af-e0d7-4638-996e-0c872a9d8233.png">

End this is the error log

```
[23-Sep-2022 09:22:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php:40
Stack trace:
#0 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#1 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Client.php(1058): GuzzleHttp\Client->__construct()
#2 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Client.php(1032): Google_Client->createDefaultHttpClient()
#3 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Client.php(356): Google_Client->getHttpClient()
#4 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Client.php(786): Google_Client->authorize()
#5 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Http/MediaFileUpload.php(307): Google_Client->execute()
#6 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Http/MediaFileUpload.php(285): Google_Http_MediaFileUpload->fetchResumeUri()
#7 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/google/apiclient/src/Google/Http/MediaFileUpload.php(120): Google_Http_MediaFileUpload->getResumeUri()
#8 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Services/Mailer/Providers/Gmail/Handler.php(82): Google_Http_MediaFileUpload->nextChunk()
#9 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Services/Mailer/Providers/Gmail/Handler.php(24): FluentMail\App\Services\Mailer\Providers\Gmail\Handler->sendViaApi()
#10 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Services/Mailer/Providers/Gmail/Handler.php(15): FluentMail\App\Services\Mailer\Providers\Gmail\Handler->postSend()
#11 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Services/Mailer/FluentPHPMailer.php(28): FluentMail\App\Services\Mailer\Providers\Gmail\Handler->send()
#12 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Functions/helpers.php(561): FluentMail\App\Services\Mailer\FluentPHPMailer->send()
#13 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/fluent-smtp.php(40): fluentMailSend()
#14 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Models/Traits/SendTestEmailTrait.php(35): wp_mail()
#15 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/app/Http/Controllers/SettingsController.php(153): FluentMail\App\Models\Settings->sendTestEmail()
#16 [internal function]: FluentMail\App\Http\Controllers\SettingsController->sendTestEmil()
#17 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/Core/Container.php(507): call_user_func_array()
#18 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/Core/Container.php(633): FluentMail\Includes\Core\Container->call()
#19 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/Core/Container.php(502): FluentMail\Includes\Core\Container->callClass()
#20 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/Core/CoreTrait.php(73): FluentMail\Includes\Core\Container->call()
#21 /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/Core/CoreTrait.php(31): FluentMail\Includes\Core\Application->FluentMail\Includes\Core\{closure}()
#22 /home/verticalvibez.huxx.dev/public_html/wp-includes/class-wp-hook.php(307): FluentMail\Includes\Core\Application->FluentMail\Includes\Core\{closure}()
#23 /home/verticalvibez.huxx.dev/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#24 /home/verticalvibez.huxx.dev/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#25 /home/verticalvibez.huxx.dev/public_html/wp-admin/admin-ajax.php(187): do_action()
#26 {main}
  thrown in /home/verticalvibez.huxx.dev/public_html/wp-content/plugins/fluent-smtp/includes/libs/google-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 40

```

If you need assistance or providing the setup with the plugin I will be more then happy to help

**Comment by techjewel** [comment]
The issue has been fixed in the latest version (2.2.1)
